"""Week 4: train the same physics-constrained transformer, but on data
generated by PyBaMM's Single Particle Model (SPM) instead of real NASA
battery measurements.

Run gen_spm.py first to produce the CSVs in week4/data/.
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from common.train import train_model, visualize_results  # noqa: E402

# --- CONFIGURATION ---
BATCH_SIZE = 32
EPOCHS = 100
LEARNING_RATE = 1e-4
SEQ_LEN = 20         # matches BINS in gen_spm.py
D_MODEL = 64
NHEAD = 4
NUM_LAYERS = 2
LAMBDA_Q = 0.3       # Constraint weight for Charge
LAMBDA_E = 0.3       # Constraint weight for Energy

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")
MAIN_CSV = os.path.join(DATA_DIR, "spm_main_binned20.csv")
PHYS_CSV = os.path.join(DATA_DIR, "spm_phys_resampled200.csv")


if __name__ == "__main__":
    if os.path.exists(MAIN_CSV) and os.path.exists(PHYS_CSV):
        model, test_loader = train_model(
            MAIN_CSV,
            PHYS_CSV,
            seq_len=SEQ_LEN,
            d_model=D_MODEL,
            nhead=NHEAD,
            num_layers=NUM_LAYERS,
            batch_size=BATCH_SIZE,
            epochs=EPOCHS,
            lr=LEARNING_RATE,
            lambda_q=LAMBDA_Q,
            lambda_e=LAMBDA_E,
        )
        visualize_results(model, test_loader)
    else:
        print("Please run gen_spm.py first to generate the CSV files in week4/data/.")
